export const ReleaseData = [
    {
        id: 1,
        title: `Blue Archive 3rd Ani Drum Covers 1`,
        releaseyear: '2024',
        brandlink: '/releases/blue-archive-3rd-anniversary-drum-covers/',
        imagelink: 'https://f4.bcbits.com/img/a1863888366_10.jpg',
        catalogtype: 'Extended Play',
        description: 'Koguma Rin',
    },
    {
        id: 2,
        title: `Macarons / Energy Drinks`,
        releaseyear: '2024',
        brandlink: '/releases/macarons-energy-drinks/',
        imagelink: 'https://f4.bcbits.com/img/a3362773476_10.jpg',
        catalogtype: 'Extended Play',
        description: 'Koguma Rin',
    },
    {
        id: 3,
        title: `Orenji`,
        releaseyear: '2025',
        brandlink: '/releases/orenji/',
        imagelink: 'https://f4.bcbits.com/img/a3613598989_10.jpg',
        catalogtype: 'Single',
        description: 'Koguma Rin',
    },
    {
        id: 4,
        title: `Kirakira`,
        subtitle: `-Adrenaline Rashu Ver.-`,
        releaseyear: '2025',
        brandlink: '/releases/kirakira/',
        imagelink: 'https://f4.bcbits.com/img/a0639790057_10.jpg',
        catalogtype: 'Single',
        description: 'Koguma Rin',
    },
    {
        id: 5,
        title: `Gogselection I`,
        subtitle: `Set I`,
        releaseyear: '2026',
        brandlink: '/releases/gogselection-i/',
        imagelink: 'https://f4.bcbits.com/img/a3943062596_10.jpg',
        catalogtype: 'Extended Play',
        description: 'Koguma Rin',
    },
    {
        id: 6,
        title: `Stars Beneath The Cosmos`,
        releaseyear: '2026',
        brandlink: '/releases/stars-beneath-the-cosmos/',
        imagelink: 'https://f4.bcbits.com/img/a3543959136_10.jpg',
        catalogtype: 'Extended Play',
        description: 'Koguma Rin',
    },
];
